CREATE TABLE Goals (
    GOAL_ID TEXT PRIMARY KEY,
    MATCH_ID TEXT,
    PID TEXT,
    DURATION INT,
    ASSIST TEXT,
    GOAL_DESC TEXT
);

COPY Goals (GOAL_ID, MATCH_ID, PID, DURATION, ASSIST, GOAL_DESC)
FROM 'C:\Users\LENOVO\OneDrive\Desktop\SQL module project\goals.csv'
DELIMITER ','
CSV HEADER;
select * from goals;

CREATE TABLE Teams (
    TEAM_NAME TEXT,
    COUNTRY TEXT,
    HOME_STADIUM TEXT
);

COPY Teams (TEAM_NAME, COUNTRY, HOME_STADIUM)
FROM 'C:\Users\LENOVO\OneDrive\Desktop\SQL module project\Teams.csv'
DELIMITER ','
CSV HEADER;


CREATE TABLE Stadiums (
    NAME TEXT,
    CITY TEXT,
    COUNTRY TEXT,
    CAPACITY INT
);

COPY Stadiums (NAME, CITY, COUNTRY, CAPACITY)
FROM 'C:\Users\LENOVO\OneDrive\Desktop\SQL module project\Stadiums.csv'
DELIMITER ','
CSV HEADER;


CREATE TABLE Players (
    PLAYER_ID TEXT PRIMARY KEY,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    NATIONALITY TEXT,
    DOB DATE,
    TEAM TEXT,
    JERSEY_NUMBER INT,
    POSITION TEXT,
    HEIGHT INT,
    WEIGHT INT,
    FOOT CHAR(1)
);

COPY Players (PLAYER_ID, FIRST_NAME, LAST_NAME, NATIONALITY, DOB, TEAM, JERSEY_NUMBER, POSITION, HEIGHT, WEIGHT, FOOT)
FROM 'C:\Users\LENOVO\OneDrive\Desktop\SQL module project\Players.csv'
DELIMITER ','
CSV HEADER;


CREATE TABLE Matches (
    MATCH_ID TEXT PRIMARY KEY,
    SEASON TEXT,
    DATE DATE,
    HOME_TEAM TEXT,
    AWAY_TEAM TEXT,
    STADIUM TEXT,
    HOME_TEAM_SCORE INT,
    AWAY_TEAM_SCORE INT,
    PENALTY_SHOOT_OUT INT,
    ATTENDANCE INT
);

COPY Matches (MATCH_ID, SEASON, DATE, HOME_TEAM, AWAY_TEAM, STADIUM, HOME_TEAM_SCORE, AWAY_TEAM_SCORE, PENALTY_SHOOT_OUT, ATTENDANCE)
FROM 'C:\Users\LENOVO\OneDrive\Desktop\SQL module project\Matches.csv'
DELIMITER ','
CSV HEADER;


